name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Lint Lua Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Lua
        uses: GoatG33k/fivem-lua-lint-action@esx-reborn
        with:
          capture: "junit.xml"
          args: "-d --formatter JUnit"
          extra_libs: "esx_reborn"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "**/junit.xml"
          fail_on_failure: 0
